dist: trusty

language: cpp

matrix:
  include:
    - name: "GCC 4.8 (Linux)"  # GCC 4.8.5 & CMake 3.9.2
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8
      env:
        - SET_COMPILER="export CC=gcc-4.8 && export CXX=g++-4.8"

    - name: "Clang 3.5 (Linux)"  # Clang 3.5.0 & CMake 3.9.2
      os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-3.5
          packages:
            - clang-3.5
      env:
        - SET_COMPILER="export CC=clang-3.5 && export CXX=clang++-3.5"

    - name: "Clang Xcode 6.4 (OSX)"  # Clang 3.6.0 & CMake 3.2.2
      os: osx
      osx_image: xcode6.4

before_install:
  - eval "${SET_COMPILER}"

script:
  - mkdir build && cd build && cmake -Dbiosoup_build_tests=ON -DCMAKE_BUILD_TYPE=Release .. && make
  - ./bin/biosoup_test

notifications:
  email:
    on_failure: always
